export default {
  locale: 'en',
  messages: {
      //common
      submit: 'Submit',
      cancel: 'Cancel',
      language: '中文',
      hello: 'hello-',
      signIn: 'Sign In',
      signOut: 'Sign Out',
      user: 'User',
      forgot: 'Forget Password',
      remember: 'Remember Me',
      register: 'Go Register Now!',
      signInTips : 'Please type in Username or Email!',
      signInPassTips : 'Please type in password!',

      //users
      edit: 'Edit',
      delete: 'Delete',
      addUser: 'Add User',
      username: 'User Name',
      password: 'Password',
      email: 'Email',
      phone: 'cellphone',
      role: 'Role',

      //menus
      home: 'Home',
      template: 'Template',
      paper: 'Paper',
      record: 'Record',
      page: 'Page',
      notFound: 'Not Found',
      permissionManage: 'Permission Manage',
      basic: 'Basic',
      routeIntercept: 'Route Intercept',

      // question
      singleChoice: 'Single Choice',
      multiChoice: 'Multi Choice',
      judge: 'Judge',
      blank: 'Blank',
      questAnswer: 'Question&Answer',
      mixing: 'Mixing',
      difficulty: 'Difficulty',
      stem: 'Stem',
      stemPlaceholder: 'Please type in stem of the question',
      choiceItem: 'Choice Items',
      choiceItemPlaceholder: 'Please type in choice items of the question',
      answer: 'Answer',
      answerPlaceholder: 'Please select the correct option',
      analysis: 'Analysis',
      analysisPlaceholder: 'Please type in analysis of the question',
      addChoiceItem: 'Add an new option',
      difficultyDescription: 'Indicate the difficulty of this question, increase from 1 to 5',
      subjectPlaceholder: 'Please select the Subject',
      subject: 'Subject',
      continueAddNext: 'Continue Add Next One',
      isReal: 'Is Real',
      isRealTrue: 'True',
      isRealFalse:  'False',
      isRealDescription: 'Description',
      description: 'Description: such as 2018.6 Beijing college entrance examination',
      recordStatus: 'Status',
      loading: 'Saving',
      success: 'Success',
      failed: 'Failed',
  }
};
