export default {
  locale: 'en',
  messages: {
      //common
      submit: 'Submit',
      save: 'Save',
      cancel: 'Cancel',
      sure: 'Sure',
      close: 'Close',
      language: '中文',
      hello: 'hello-',
      signIn: 'Sign In',
      signOut: 'Sign Out',
      user: 'User',
      forgot: 'Forget Password',
      remember: 'Remember Me',
      register: 'Go Register Now!',
      signInTips : 'Please type in Username or Email!',
      signInPassTips : 'Please type in Password!',
      sureToDelete: "Sure To Delete?",

      title: 'Title',
      titlePlaceholder: 'Please type in Title',

      //users
      edit: 'Edit',
      delete: 'Delete',
      addUser: 'Add User',
      username: 'User Name',
      password: 'Password',
      email: 'Email',
      phone: 'cellphone',
      role: 'Role',
      admin: 'Administrator',
      administrator: 'Super Administrator',
      teacher: 'Teacher',
      usernamePlaceHolder: 'Please type in Username',
      passwordPlaceHolder: 'Please type in Password',
      emailPlaceHolder: 'Please type in Email',
      phonePlaceHolder: 'Please type in Phone Number',
      rolePlaceHolder: 'Please select Role',

      //menus
      home: 'Home',
      template: 'Template',
      paper: 'Paper',
      record: 'Record',
      page: 'Page',
      notFound: 'Not Found',
      permissionManage: 'Permission Manage',
      basic: 'Basic',
      routeIntercept: 'Route Intercept',
      quests: 'Questions',

      // question
      singleChoice: 'Single Choice',
      multiChoice: 'Multi Choice',
      judge: 'Judge',
      blank: 'Blank',
      questAnswer: 'Question&Answer',
      mixing: 'Mixing',
      difficulty: 'Difficulty',
      stem: 'Stem',
      stemPlaceholder: 'Please type in stem of the question',
      choiceItem: 'Choice Items',
      choiceItemPlaceholder: 'Please type in choice items of the question',
      answer: 'Answer',
      answerPlaceholder: 'Please select the correct option',
      analysis: 'Analysis',
      analysisPlaceholder: 'Please type in analysis of the question',
      addChoiceItem: 'Add an new option',
      difficultyDescription: 'Indicate the difficulty of this question, increase from 1 to 5',
      subjectPlaceholder: 'Please select the Subject',
      subject: 'Subject',
      continueAddNext: 'Continue Add Next One',
      isReal: 'Is Real',
      isRealTrue: 'True',
      isRealFalse:  'False',
      isRealDescription: 'Description',
      description: 'Description: such as 2018.6 Beijing college entrance examination',
      recordStatus: 'Status',
      loading: 'Saving',
      success: 'Success',
      failed: 'Failed',
      right: 'Right',
      wrong: 'Wrong',
      questType: "Question Type",
      recordQuests: 'Record Questions',

      // subjects
      systemDefault: 'System Default',
      userDefinition: 'User Definition',
      tagManagement: 'Tag Management',
      tagManagementNotes1: '标签可用于设置试题的属性,在生成试卷时匹配更精确地题型',
      tagManagementNotes2: '标签用于对题型做更细致的分类,比如问答题下可以设置"证明题"标签,组合题下可以设置"短文阅读"标签',
      newTag: 'New Tag',
      sharedTagManagement: 'Shared Tag Management',
      sharedTag: 'Shared Tags',
      subjectTag: 'Subject Tags',
      createSubject: 'Create Subject',

      // templates
      creatTemplate: 'Create Template',
      addSingleChoice: 'Add Single Choice',
      addMultiChoice: 'Add Multiple Choice',
      addJudge: 'Add Judge',
      addBlank: 'Add Blank',
      addQuestAnswer: 'Add Question&Answer',
      addMixing: 'Add Mixing',
      addSubQuest: 'Add Sub Questions',
      subQuest: "Sub Quest",
      addQuestType: 'Add Question type',
      tag: 'Tag',
      selectTags: 'Select Tags',
      moveUp: "Move Up",
      moveDown: "Move Down",
      questTypeSet: "Set Questions",
      number: "Number",
      score: "Score",
      offset: "Offset",
      createPaper: "Creat Paper",
      copy: "Copy",
      subQuestNum: "Sub Question Number",
      setAlias: "Set Alias",
      AliasDescription: 'Set the name of the question displayed on the paper, such as the combination question can be set to Reading Comprehension',
      scoreTotal: "Total",

      //paper
      createAnswerCard: "Create Answer Card"
  }
};
