export default {
  locale: 'zh',
  messages: {
      //common
      submit: '提交',
      save: '保存',
      cancel: '取消',
      sure: '确定',
      close: '关闭',
      action: '操作',
      language: 'English',
      hello: '你好-',
      signIn: '登录',
      signOut: '退出登录',
      user: '用户',
      forgot: '忘记密码',
      remember: '记住我',
      register: '现在就去注册!',
      signInTips : '请输入用户名或邮箱!',
      signInPassTips : '请输入密码!',
      sureToDelete: "确定删除吗？",

      title: '标题',
      titlePlaceholder: '请输入标题',

      //users
      edit: '编辑',
      delete: '删除',
      addUser: '新增用户',
      username: '名称',
      password: '密码',
      email: '邮箱',
      phone: '手机',
      role: '角色',
      admin: '管理员',
      administrator: '超级管理员',
      teacher: '教师',
      usernamePlaceHolder: '请输入姓名',
      passwordPlaceHolder: '请输入密码',
      emailPlaceHolder: '请输入邮箱',
      phonePlaceHolder: '请输入手机号码',
      rolePlaceHolder: '请选择角色',

      //menus
      home: '首页',
      template: '模板',
      paper: '试卷',
      record: '录入',
      page: '页面',
      notFound: 'Not Found',
      permissionManage: '权限管理',
      basic: '基础演示',
      routeIntercept: '路由拦截',
      quests: '题库',

      // question
      singleChoice: '单选题',
      multiChoice: '多选题',
      judge: '判断题',
      blank: '填空题',
      questAnswer: '问答题',
      mixing: '组合题',
      difficulty: '难度',
      stem: '题干',
      stemPlaceholder: '请输入问题的题干',
      choiceItem: '选项',
      choiceItemPlaceholder: '请输入问题的选项',
      answer: '答案',
      answerPlaceholder: '请选择正确的选项',
      analysis: '解析',
      analysisPlaceholder: '请输入问题的解析',
      addChoiceItem: '新增一个选项',
      difficultyDescription: '指明此题的难易程度. 从1到5难度增加',
      subjectPlaceholder: '请选择科目',
      subject: '科目',
      continueAddNext: '继续录入下一题',
      isReal: '是否真题',
      isRealTrue: '是',
      isRealFalse:  '否',
      isRealDescription: '描述',
      descriptionPlaceholder: '描述: 例如2018.6月北京高考真题',
      recordStatus: '状态',
      loading: '保存中',
      success: '成功',
      failed: '失败',
      right: '对',
      wrong: '错',
      questType: "题型",
      recordQuests: '录入试题',

      // subjects
      systemDefault: '系统内置',
      userDefinition: '用户创建',
      tagUsage: "标签作用",
      tagManagement: '标签管理',
      tagManagementNotes1: '标签可用于设置试题的属性,在生成试卷时匹配更精确地题型',
      tagManagementNotes2: '标签用于对题型做更细致的分类,比如问答题下可以设置"证明题"标签,组合题下可以设置"短文阅读"标签',
      newTag: '新建标签',
      sharedTagManagement: '共享标签管理',
      sharedTag: '共享标签',
      subjectTag: '科目标签',
      createSubject: '新建科目',
      subjectName: '科目名称',
      subjectNamePlaceholder: '请输入科目名称',
      subjectCode: '科目编码',
      subjectCodePlaceholder: '请输入科目编码',

      // templates
      creatTemplate: '创建模板',
      addSingleChoice: '增加单择题',
      addMultiChoice: '增加多选题',
      addJudge: '增加判断题',
      addBlank: '增加填空题',
      addQuestAnswer: '增加问答题',
      addMixing: '增加组合题',
      addSubQuest: '新增子题目',
      subQuest: "子题目",
      addQuestType: '新增题型',
      tag: '标签',
      selectTags: '选择标签',
      moveUp: "上移",
      moveDown: "下移",
      questTypeSet: "题型设置",
      number: "数量",
      score: "分数",
      offset: "偏移量",
      createPaper: "生成试卷",
      copy: "复制",
      subQuestNum: "子题数量",
      alias: "别名",
      setAlias: "设置别名",
      AliasDescription: '设置在试卷上展示的试题名称,如组合题可以设置为阅读理解',
      scoreTotal: "总分",

      //paper
      createAnswerSheet: "生成答题卡",
      viewAnalysis: '查看解析',
      printTips: "答题卡生成后, 在菜单选择打印即可",
      paperSize: "版面大小",
      createPaperTips: "试卷生成中",
      sumPrefix: "共",
      questSuffix: "题",
      perQuestPrefix: "每题",
      scoreSuffix: "分",
      createTime: '创建时间',
      comma: '，',
      colon: '：',
      pauseSymbol: '、',
      pNumber1: '一',
      pNumber2: '二',
      pNumber3: '三',
      pNumber4: '四',
      pNumber5: '五',
      pNumber6: '六',
      pNumber7: '七',
      pNumber8: '八',
      pNumber9: '九',
      pNumber10: '十',
      pNumber11: '十一',
      pNumber12: '十二',
      pNumber13: '十三',
      pNumber14: '十四',
      pNumber15: '十五',

      //Answer sheet
      answerSheet : '答题卡',
      admissionNumber: '准考证号',
      studentNumber: '学号',
      barCode: '条形码',
      identifierCode: '考生识别码',
      identifierCodeLength: '识别码长度',
      columns: '版面列数',
      column: '列',
      sheetLayout: "版面布局",
      horizon: "水平",
      vertical: "垂直",
      identifierInfo: '考生信息选项',
      identifierInfoPlaceholder: '请选择需要的考生信息选项,也可以直接输入',
      name: '姓名',
      school: '学校',


  }
};
