export default {
  locale: 'zh',
  messages: {
      //common
      submit: '提交',
      save: '保存',
      cancel: '取消',
      language: 'English',
      hello: '你好-',
      signIn: '登录',
      signOut: '退出登录',
      user: '用户',
      forgot: '忘记密码',
      remember: '记住我',
      register: '现在就去注册!',
      signInTips : '请输入用户名或邮箱!',
      signInPassTips : '请输入密码!',

      title: '标题',
      titlePlaceholder: '请输入标题',

      //users
      edit: '修改',
      delete: '删除',
      addUser: '新增用户',
      username: '名称',
      password: '密码',
      email: '邮箱',
      phone: '手机',
      role: '角色',
      admin: '管理员',
      administrator: '超级管理员',
      teacher: '教师',
      usernamePlaceHolder: '请输入姓名',
      passwordPlaceHolder: '请输入密码',
      emailPlaceHolder: '请输入邮箱',
      phonePlaceHolder: '请输入手机号码',
      rolePlaceHolder: '请选择角色',

      //menus
      home: '首页',
      template: '模板',
      paper: '试卷',
      record: '录入',
      page: '页面',
      notFound: 'Not Found',
      permissionManage: '权限管理',
      basic: '基础演示',
      routeIntercept: '路由拦截',
      quests: '题库',

      // question
      singleChoice: '单选题',
      multiChoice: '多选题',
      judge: '判断题',
      blank: '填空题',
      questAnswer: '问答题',
      mixing: '组合题',
      difficulty: '难度',
      stem: '题干',
      stemPlaceholder: '请输入问题的题干',
      choiceItem: '选项',
      choiceItemPlaceholder: '请输入问题的选项',
      answer: '答案',
      answerPlaceholder: '请选择正确的选项',
      analysis: '解析',
      analysisPlaceholder: '请输入问题的解析',
      addChoiceItem: '新增一个选项',
      difficultyDescription: '指明此题的难易程度. 从1到5难度增加',
      subjectPlaceholder: '请选择科目',
      subject: '科目',
      continueAddNext: '继续录入下一题',
      isReal: '是否真题',
      isRealTrue: '是',
      isRealFalse:  '否',
      isRealDescription: '描述',
      descriptionPlaceholder: '描述: 例如2018.6月北京高考真题',
      recordStatus: '状态',
      loading: '保存中',
      success: '成功',
      failed: '失败',
      right: '对',
      wrong: '错',

      // subjects
      systemDefault: '系统内置',
      userDefinition: '用户创建',

      // templates
      creatTemplate: '创建模板',
      addSingleChoice: '增加单择题',
      addMultiChoice: '增加多选题',
      addJudge: '增加判断题',
      addBlank: '增加填空题',
      addQuestAnswer: '增加问答题',
      addMixing: '增加组合题',
      addSubQuest: '新增子题目'

  }
};
